### ISSUE TITLE
Getting "Segmentation fault" while installing the package AND "ue4 build" fails.

### ISSUE THREAD

**Issue by meetakshay99** [adamrehn/conan-ue4cli#10]
Installing ue4cli and conan-ue4cli on linux host prints "Segmentation Fault" at the end.
Then I ran commands "ue4 setroot" and "ue4 conan generate" and they succeeded.
But when I tried to build the app "ue4 build", it failed.
"ue4 build" works for 4.26 in a container. This issue happened on linux host.
Below is the complete log showing all the above-mentioned commands being performed:

```
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$ pip3 install ue4cli conan-ue4cli
Collecting ue4cli
  Using cached https://files.pythonhosted.org/packages/34/67/a1b1a70e9ed754a4195d31501f1adc9d195039975c69aac06ca65b71b018/ue4cli-0.0.49-py3-none-any.whl
Collecting conan-ue4cli
  Using cached https://files.pythonhosted.org/packages/ff/5a/1c2833507d79ac62c1f96ff78aff0c079611177de142e763604b50391cdf/conan_ue4cli-0.0.35-py3-none-any.whl
Collecting setuptools>=38.6.0 (from ue4cli)
  Using cached https://files.pythonhosted.org/packages/3d/f2/1489d3b6c72d68bf79cd0fba6b6c7497df4ebf7d40970e2d7eceb8d0ea9c/setuptools-51.0.0-py3-none-any.whl
Collecting wheel>=0.31.0 (from ue4cli)
  Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Collecting twine>=1.11.0 (from ue4cli)
  Using cached https://files.pythonhosted.org/packages/ad/db/b2c65078b783c6694bdfa0911bbbe0e2be7fcbc98ff23a99b8be544906b6/twine-3.2.0-py3-none-any.whl
Collecting shellescape (from ue4cli)
  Using cached https://files.pythonhosted.org/packages/d0/f4/0081137fceff5779cd4205c1e96657e41cc2d2d56c940dc8eeb6111780f7/shellescape-3.8.1-py2.py3-none-any.whl
Collecting conan>=1.7.4 (from conan-ue4cli)
Collecting importlib-metadata; python_version < "3.8" (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/7a/85/ac225e35048e050a6351b6f1251cdb2b6060092f2c6840aff1d6319941b1/importlib_metadata-3.3.0-py3-none-any.whl
Collecting requests-toolbelt!=0.9.0,>=0.8.0 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting colorama>=0.4.3 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting requests>=2.20 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl
Collecting readme-renderer>=21.0 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/54/18/0adfcac99c08a6d45947e5da4e1388a7bb9957502a2b4ad12176fed6aeaf/readme_renderer-28.0-py2.py3-none-any.whl
Collecting tqdm>=4.14 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/8a/54/115f0c28a61d56674c3a5e05c46d6c3523ad196e1dcd3e2d8b119026df36/tqdm-4.54.1-py2.py3-none-any.whl
Collecting rfc3986>=1.4.0 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/78/be/7b8b99fd74ff5684225f50dd0e865393d2265656ef3b4ba9eaaaffe622b8/rfc3986-1.4.0-py2.py3-none-any.whl
Collecting keyring>=15.1 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/53/14/1c952bcd21255f42f9ba0280d3abd8074dca2c27d136eb749b98ab478f72/keyring-21.5.0-py3-none-any.whl
Collecting pkginfo>=1.4.2 (from twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/4f/3c/535287349af1b117e082f8e77feca52fbe2fdf61ef1e6da6bcc2a72a3a79/pkginfo-1.6.1-py2.py3-none-any.whl
Collecting six<=1.15.0,>=1.10.0 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting Jinja2<3,>=2.9 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting node-semver==0.6.1 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/08/51/6cf3a2b18ca35cbe4ad3c7538a7c3dc0cb24e71629fb16e729c137d06432/node_semver-0.6.1-py3-none-any.whl
Collecting distro<=1.5.0,>=1.0.2 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl
Collecting pygments<3.0,>=2.0 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/85/c5/c437c383d5917fae9782eb6588bec8aff931afe13c76b9e8c03dacee9beb/Pygments-2.7.3-py3-none-any.whl
Collecting fasteners>=0.14.1 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
Collecting pluginbase>=0.5 (from conan>=1.7.4->conan-ue4cli)
Collecting python-dateutil<3,>=2.7.0 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting patch-ng<1.18,>=1.17.4 (from conan>=1.7.4->conan-ue4cli)
Collecting PyYAML<6.0,>=3.11 (from conan>=1.7.4->conan-ue4cli)
Collecting future<0.19.0,>=0.16.0 (from conan>=1.7.4->conan-ue4cli)
Collecting bottle<0.13,>=0.12.8 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/bf/44/aeafdd6ca05a8e1c3f91eeeb272a202d5cb1b3b23730a5ca686a81c48d24/bottle-0.12.19-py3-none-any.whl
Collecting deprecation<2.1,>=2.0 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/b9/2a/d5084a8781398cea745c01237b95d9762c382697c63760a95cc6a814ad3a/deprecation-2.0.7-py2.py3-none-any.whl
Collecting PyJWT<2.0.0,>=1.4.0 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting urllib3!=1.25.4,!=1.25.5,<1.26 (from conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.20->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests>=2.20->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests>=2.20->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting docutils>=0.13.1 (from readme-renderer>=21.0->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl
Collecting bleach>=2.1.0 (from readme-renderer>=21.0->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/03/c8/b7ed0dfea5cb287907bd22c5ff7c3ed0a65b346f2a4cf916eb9e83be66b3/bleach-3.2.1-py2.py3-none-any.whl
Collecting jeepney>=0.4.2; sys_platform == "linux" (from keyring>=15.1->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/51/b0/a6ea72741aaac3f37fb96d195e4ee576a103c4c04e279bc6b446a70960e1/jeepney-0.6.0-py3-none-any.whl
Collecting SecretStorage>=3.2; sys_platform == "linux" (from keyring>=15.1->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/63/a2/a6d9099b14eb5dbbb04fb722d2b5322688f8f99b471bdf2097e33efa8091/SecretStorage-3.3.0-py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2<3,>=2.9->conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting monotonic>=0.1 (from fasteners>=0.14.1->conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting packaging (from deprecation<2.1,>=2.0->conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/b1/a7/588bfa063e7763247ab6f7e1d994e331b85e0e7d09f853c59a6eb9696974/packaging-20.8-py2.py3-none-any.whl
Collecting webencodings (from bleach>=2.1.0->readme-renderer>=21.0->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/7c/b6/1f3dd48a22fcd56f19e6cfa95f74ff0a64b046306354e1bd2b936b7c9ab4/cryptography-3.3.1-cp36-abi3-manylinux1_x86_64.whl
Collecting pyparsing>=2.0.2 (from packaging->deprecation<2.1,>=2.0->conan>=1.7.4->conan-ue4cli)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/1c/1a/90fa7e7ee05d91d0339ef264bd8c008f57292aba4a91ec512a0bbb379d1d/cffi-1.14.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine>=1.11.0->ue4cli)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel, typing-extensions, zipp, importlib-metadata, certifi, idna, urllib3, chardet, requests, requests-toolbelt, colorama, six, pygments, docutils, pyparsing, packaging, webencodings, bleach, readme-renderer, tqdm, rfc3986, jeepney, pycparser, cffi, cryptography, SecretStorage, keyring, pkginfo, twine, shellescape, ue4cli, MarkupSafe, Jinja2, node-semver, distro, monotonic, fasteners, pluginbase, python-dateutil, patch-ng, PyYAML, future, bottle, deprecation, PyJWT, conan, conan-ue4cli
Segmentation fault
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$ ue4 setroot /home/ubuntu/Akshay/UnrealEngine/
Using user-specified engine root: /home/ubuntu/Akshay/UnrealEngine
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$ ue4 conan generate
Using user-specified engine root: /home/ubuntu/Akshay/UnrealEngine
Removing the "ue4.26-Linux-x86_64-unknown-linux-gnu" Conan profile if it already exists...
Removing any previous versions of profile base packages...
Creating "ue4.26-Linux-x86_64-unknown-linux-gnu" Conan profile using autodetected settings...
Installing profile base packages...
Copying the "ue4.26-Linux-x86_64-unknown-linux-gnu" Conan profile into a new profile named "ue4"...
Retrieving thirdparty library list from UBT...
Removing any previous versions of generated wrapper packages for 4.26...
Generating and installing toolchain wrapper package...
  Wrapping clang: /home/ubuntu/Akshay/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang
  Wrapping lib++: /home/ubuntu/Akshay/UnrealEngine/Engine/Source/ThirdParty/Linux/LibCxx/lib/Linux/x86_64-unknown-linux-gnu/libc++.a
Generating and installing wrapper package for APEX...
Generating and installing wrapper package for Asio...
Generating and installing wrapper package for CEF3...
Generating and installing wrapper package for Crunch...
Generating and installing wrapper package for Eigen...
Generating and installing wrapper package for Expat...
Generating and installing wrapper package for FBX...
Generating and installing wrapper package for ForsythTriOptimizer...
Generating and installing wrapper package for FreeImage...
Generating and installing wrapper package for FreeType2...
Generating and installing wrapper package for GeForceNOW...
Generating and installing wrapper package for GlsLang...
Generating and installing wrapper package for GoogleARCoreSDK...
Generating and installing wrapper package for HLSLCC...
Generating and installing wrapper package for HarfBuzz...
Generating and installing wrapper package for ICU...
Generating and installing wrapper package for IntelISPC...
Generating and installing wrapper package for IntelISPCTexComp...
Generating and installing wrapper package for IntelTBB...
Generating and installing wrapper package for Kiss_FFT...
Generating and installing wrapper package for MCPP...
Generating and installing wrapper package for MikkTSpace...
Generating and installing wrapper package for OpenGL...
Generating and installing wrapper package for OpenSSL...
Generating and installing wrapper package for OpenSubdiv...
Generating and installing wrapper package for OpenVR...
Generating and installing wrapper package for Perforce...
Generating and installing wrapper package for PhysX...
Generating and installing wrapper package for PhysXCookingLib...
Generating and installing wrapper package for Python3...
Generating and installing wrapper package for QualcommTextureConverter...
Generating and installing wrapper package for SDL2...
Generating and installing wrapper package for SPIRVReflect...
Generating and installing wrapper package for ShaderConductor...
Generating and installing wrapper package for SpeedTree...
Generating and installing wrapper package for Steamworks...
Generating and installing wrapper package for UELibSampleRate...
Generating and installing wrapper package for UEOgg...
Generating and installing wrapper package for UEOpenExr...
Generating and installing wrapper package for UElibJPG...
Generating and installing wrapper package for UElibPNG...
Generating and installing wrapper package for VHACD...
Generating and installing wrapper package for Vorbis...
Generating and installing wrapper package for VorbisFile...
Generating and installing wrapper package for Vulkan...
Generating and installing wrapper package for coremod...
Generating and installing wrapper package for jemalloc...
Generating and installing wrapper package for libOpus...
Generating and installing wrapper package for libWebSockets...
Generating and installing wrapper package for libcurl...
Generating and installing wrapper package for libstrophe...
Generating and installing wrapper package for nvTessLib...
Generating and installing wrapper package for nvTextureTools...
Generating and installing wrapper package for nvTriStrip...
Generating and installing wrapper package for zlib...
Done.
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealEngine$ cd ..
ubuntu@ip-172-31-8-169:~/Akshay$ cd UnrealTestApp/TestApp
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$ ue4 build
Using user-specified engine root: /home/ubuntu/Akshay/UnrealEngine
Ensuring ShaderCompileWorker is built before building project Editor modules...
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ue4cli/cli.py", line 76, in <lambda>
    'action': lambda m, args: m.buildDescriptor(os.getcwd(), args.pop(0) if (len(args) > 0 and args[0].startswith('-') == False) else 'Development', args.pop(0) if (len(args) > 0 and args[0].startswith('-') == False) else 'Editor', args),
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ue4cli/UnrealManagerBase.py", line 342, in buildDescriptor
    self.buildTarget('ShaderCompileWorker', 'Development', [], capture=suppressOutput)
TypeError: buildTarget() got an unexpected keyword argument 'capture'
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$ pip3 show ue4cli
Name: ue4cli
Version: 0.0.49
Summary: Command-line interface for Unreal Engine 4
Home-page: http://github.com/adamrehn/ue4cli
Author: Adam Rehn
Author-email: adam@adamrehn.com
License: MIT
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: setuptools, shellescape, twine, wheel
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$ pip4 show conan-ue4cli

Command 'pip4' not found, did you mean:

  command 'pip2' from deb python-pip
  command 'pdp4' from deb simh
  command 'pip' from deb python-pip
  command 'pip3' from deb python3-pip

Try: sudo apt install <deb name>

ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$ pip3 show conan-ue4cli
Name: conan-ue4cli
Version: 0.0.35
Summary: Integrate third-party libraries into the Unreal Engine with Conan
Home-page: http://github.com/adamrehn/conan-ue4cli
Author: Adam Rehn
Author-email: adam@adamrehn.com
License: MIT
Location: /home/ubuntu/.local/lib/python3.6/site-packages
Requires: conan, setuptools, wheel, ue4cli
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$
ubuntu@ip-172-31-8-169:~/Akshay/UnrealTestApp/TestApp$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

```

**Comment by iwer** [comment]
I didn't notice the segfault but have the same problem with "ue4 build" with ubuntu 20.10.

If the engine components (namely the ShaderCompileWorker) are already built from source you can use the "-notools" flag as temporary work-around. This omits the check and build of ShaderCompileWorker.
`
$ ue4 build -notools`

**Comment by adamrehn** [comment]
Whoops, my bad!

**Comment by adamrehn** [comment]
This is fixed in <https://github.com/adamrehn/ue4cli/commit/72146610532d5e9dea6368f84b8a86138cf64319>, which is now live in ue4cli version 0.0.50. Apologies for that silly oversight, evidently I didn't test the `ue4 build` command for regressions when I implemented the [ue4 build-target](https://docs.adamrehn.com/ue4cli/engine-commands/build-target) command the other day.

@meetakshay99 I'm not sure what's going on with regards to that segmentation fault, but I have to assume it's something related to pip itself given that the packages all appear to install correctly.
