### ISSUE TITLE
Broken with conan 1.12

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/conan-ue4cli#2]
Attempting to build packages (especially the recipe packages) with conan version 1.12 (uploaded today) fails with the following:

```
$ ue4 conan build cares-ue4 -user=somebody
Using user-specified engine root: /UnrealInstalled/
Traceback (most recent call last):
  File "/home/me/.pyenv/ue4cli/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/ue4cli/cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conan_ue4cli/main.py", line 34, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conan_ue4cli/build.py", line 325, in build
    buildOrder = builder.computeBuildOrder(packages)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conan_ue4cli/build.py", line 242, in computeBuildOrder
    graph = self.buildDependencyGraph(packages)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conan_ue4cli/build.py", line 181, in buildDependencyGraph
    deps = self.extractDependencies(current)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conan_ue4cli/build.py", line 146, in extractDependencies
    recipe = recipes[0](None, None, user=self.user, channel=self.channel)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conans/model/conan_file.py", line 120, in __init__
    self.output = ScopedOutput(display_name, output)
  File "/home/me/.pyenv/ue4cli/lib/python3.6/site-packages/conans/client/output.py", line 115, in __init__
    self._stream = output._stream
AttributeError: 'NoneType' object has no attribute '_stream'
```

This should be killing the `ue4-full` docker image shortly...

**Comment by adamrehn** [comment]
Thanks for letting me know about this! Fixed in version 0.0.11.
